# Week 4 : Pandas, Data loading, Storage and File formats Exercises

In [1]:
import numpy as np
import pandas as pd

Create a Series from a list of integers representing daily
temperatures (in Celsius) over a week. Assign index labels as day
of the week.

a. Find and print the average (mean) temperature for the week.

b. Identify and print the maximum and minimum temperatures and their respective days.

c. Display the temperatures greater than a specific value.

d. Convert all temperatures to Fahrenheit.

e. Print the days had temperatures above the average

In [ ]:
temps = pd.Series(
    [30, 32, 29, 35, 33, 31, 28],
    index=["Monday", "Tuesday", "Wednesday", "Thursday",
           "Friday", "Saturday", "Sunday"]
)

In [3]:
print("The temperatures are : \n")
temps

The temperatures are :

Monday       30
Tuesday      32
Wednesday    29
Thursday     35
Friday       33
Saturday     31
Sunday       28
dtype: int64

In [7]:
print("The average of all temperatures is : ", temps.mean())
print("\nThe maximum temperature and its day is : ")
print("\nDay:", temps.idxmax())
print("\nTemperature:", temps.max())
print("\nThe minimum temperature and its day is : ")
print("\nDay:", temps.idxmin())
print("\nTemperature:", temps.min())

The average of all temperatures is :  31.142857142857142

The maximum temperature and its day is :

Day: Thursday

Temperature: 35

The minimum temperature and its day is :

Day: Sunday

Temperature: 28

In [11]:
value = int(input("Enter a specific temperature value : "))
print(f"Temperatures above the given value of {value} are : ")
print(temps[temps>value])

Temperatures above the given value of 30 are :
Tuesday     32
Thursday    35
Friday      33
Saturday    31
dtype: int64

In [10]:
fahrenheit = (temps*9/5) +32
print("The temperatures in fahrenheits are : ")
fahrenheit

The temperatures in fahrenheits are :

Monday       86.0
Tuesday      89.6
Wednesday    84.2
Thursday     95.0
Friday       91.4
Saturday     87.8
Sunday       82.4
dtype: float64

In [15]:
print(f"The temperatures above the mean temperature of {temps.mean():.2f} are : ")
temps[temps>temps.mean()]

The temperatures above the mean temperature of 31.14 are :

Tuesday     32
Thursday    35
Friday      33
dtype: int64

Create a data frame with details of 10 students and columns as Roll Number, Name, Gender, Marks1, Marks2, Marks3.

a. Create a new column with total marks

b. Find the lowest marks in Marks1

c. Find the Highest marks in Marks2

d. Find the average marks in Marks3

e. Find student name with highest average

f. Find how many students failed in Marks2 (<40)

In [16]:
students = pd.DataFrame({
    "Roll Number": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Arun","Rahul","Priya","Sneha","Rohan","Amit","Neha","Kiran","Anjali","Vikram"],
    "Gender": ["M","M","F","F","M","M","F","M","F","M"],
    "Marks1": [78,45,89,67,90,34,76,55,81,69],
    "Marks2": [88,39,76,91,52,45,67,33,84,71],
    "Marks3": [80,60,92,75,88,50,79,65,90,73]
})

students

   Roll Number    Name Gender  Marks1  Marks2  Marks3
0          101    Arun      M      78      88      80
1          102   Rahul      M      45      39      60
2          103   Priya      F      89      76      92
3          104   Sneha      F      67      91      75
4          105   Rohan      M      90      52      88
5          106    Amit      M      34      45      50
6          107    Neha      F      76      67      79
7          108   Kiran      M      55      33      65
8          109  Anjali      F      81      84      90
9          110  Vikram      M      69      71      73

In [17]:
students["Total"] = students["Marks1"]+students["Marks2"]+students["Marks3"]
students

   Roll Number    Name Gender  Marks1  Marks2  Marks3  Total
0          101    Arun      M      78      88      80    246
1          102   Rahul      M      45      39      60    144
2          103   Priya      F      89      76      92    257
3          104   Sneha      F      67      91      75    233
4          105   Rohan      M      90      52      88    230
5          106    Amit      M      34      45      50    129
6          107    Neha      F      76      67      79    222
7          108   Kiran      M      55      33      65    153
8          109  Anjali      F      81      84      90    255
9          110  Vikram      M      69      71      73    213

In [19]:
print("Lowest marks in Marks1 : ", students["Marks1"].min())
print("Highest marks in Marks2 : ", students["Marks2"].max())
print("Average marks in Marks3 : ", students["Marks3"].mean())

Lowest marks in Marks1 :  34
Highest marks in Marks2 :  91
Average marks in Marks3 :  75.2

In [32]:
students["Average"] = students["Total"]/3
students

   Roll Number    Name Gender  Marks1  Marks2  Marks3  Total    Average
0          101    Arun      M      78      88      80    246  82.000000
1          102   Rahul      M      45      39      60    144  48.000000
2          103   Priya      F      89      76      92    257  85.666667
3          104   Sneha      F      67      91      75    233  77.666667
4          105   Rohan      M      90      52      88    230  76.666667
5          106    Amit      M      34      45      50    129  43.000000
6          107    Neha      F      76      67      79    222  74.000000
7          108   Kiran      M      55      33      65    153  51.000000
8          109  Anjali      F      81      84      90    255  85.000000
9          110  Vikram      M      69      71      73    213  71.000000

In [33]:
print("Student with highest average:", students.loc[students["Average"].idxmax(), "Name"])

Student with highest average: Priya

In [36]:
failed = students["Marks2"]<40
print("Total number of people who failed in marks2 is : ", failed.sum())

Total number of people who failed in marks2 is :  2